### ISSUE TITLE
[Admin] The assignee controller

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#18]
Activation of an assignee should allow to change between the 3 statuses: accepted, rejected, pending. One an activity has entries, this shouldn't be modifiable anymore.

This page also loses the reference to its parent activity and task.
![image](https://user-images.githubusercontent.com/1401520/95214255-00173b00-07f0-11eb-90c3-4b1a1cd6f247.png)

- [x] It should show the parent activity and a way to return to it
- [x] It should show the parent task
eg: `Some task > Some activity > Assignees`
- [x] There's only one button to accept the assignees. It should be able to at least edit them (and change the status).
- [x] Members pending to be accepted should be displayed first, members rejected last.
- [x] Members pending to be accepted should be displayed with some visual effect (eg a background color)
- [ ] Prevent assignee status from being changed once the activity has time entries
- [x] The admin assignee_controller needs more test coverage

**Comment by verarojman** [comment]
⚠️ Moving "Prevent assignee status from being changed once the activity has time entries" to new issue
