### ISSUE TITLE
[Admin] The tasks controller

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#19]
- [ ] It should show if there's pending assignees (or the las 5 for instance) with a link to their administration page to accept/reject.
- [x] the "folder" icon is weird, we could find a better icon to set the activities. 
- [ ] Test coverage should include all the methods

**Comment by verarojman** [comment]
I think "It should show if there's pending assignees (or the las 5 for instance) with a link to their administration page to accept/reject." is contemplated in #10
