### ISSUE TITLE
[Admin] Create a reports page

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#24]
The admin should have a reports page where to view times for each user in a tabulated fashion.

- [ ] It should list all the accepted assignees, paginated, for all tasks and showing the accumulated time.
- [ ] It should have a filter for tasks, assignee or activity.
- [ ] It should have unit tests
- [ ] It should have integration (system) tests

**Comment by verarojman** [comment]
![Screenshot from 2021-01-22 16-27-05](https://user-images.githubusercontent.com/8806781/105510230-b2570d80-5cce-11eb-9e91-9428fe50a7dc.png)

**Comment by verarojman** [comment]
![Uploading Screenshot from 2021-01-22 16-35-31.png…]()
