### ISSUE TITLE
tweak the page for non-logged users

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#49]
Non-logged users are welcomed with a rather ugly page:
![image](https://user-images.githubusercontent.com/1401520/99533940-f2d09d00-29a6-11eb-84c6-8bf7289f8dfc.png)

Perhaps just show the same page as per logged users:
![image](https://user-images.githubusercontent.com/1401520/99534198-52c74380-29a7-11eb-8866-41220319750e.png)

An use the login modal window when clicking on the join activity

- [ ] put some imagination in it
- [ ] when login, back to the component

- [ ] When component published but no published activites, show info message

**Comment by verarojman** [comment]
Done!
![image](https://user-images.githubusercontent.com/8806781/105053465-4035bd00-5a71-11eb-80be-6b8acfda79dd.png)
