### ISSUE TITLE
tos_accepted_at missing

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-module-time_tracker#58]
this field is not updated anywhere? at least not when a user request to join an activity.

This causes milestone that use the method `user_joined_at` to fail

In fact, we need to decide where to put the TOS and how the user should accept them.

**Comment by verarojman** [comment]
Fixed in https://github.com/Platoniq/decidim-module-time_tracker/commit/b52fa77da0055a81c68f7089ca47c8bcaadfa38a
